### ISSUE TITLE
403 instead of 200 when using api cloud keys 

### ISSUE THREAD

**Issue by Basma1912** [Dabz/ccloudexporter#26]
I started using the latest image and i am getting 403 instead of 200 on posting https://api.telemetry.confluent.cloud//v1/metrics/cloud/query .. 

and i am not getting all the metrics per topic 

Received status code 403 instead of 200 for POST on https://api.telemetry.confluent.cloud//v1/metrics/cloud/query with {"aggregations":[{"agg":"SUM","metric":"io.confluent.kafka.server/received_bytes"}],"filter":{"op":"AND","filters":[{"field":"metric.label.cluster_id","op":"EQ","value":"/bin/sh"}]},"granularity":"PT1M","group_by":["metric.label.topic","metric.label.cluster_id"],"intervals":["2020-04-26T23:03:59Z/2020-04-26T23:04:59Z"],"limit":1000}

never got the 403 when using the Dockerfile on Tree 296442c077 --  ( but the size of the image is huge )

**Comment by Basma1912** [comment]
never got the 403 when using the Dockerfile on Tree 296442c077 --

**Comment by Dabz** [comment]
Hi @Basma1912 

Looking quickly at the log, it seems that the problem is due as the cluster id is not properly populated: `"field":"metric.label.cluster_id","op":"EQ","value":"/bin/sh"` (I doubt that your cluster id is /bin/sh).

Can you try running:  `docker run --network host -e CCLOUD_USER=$CCLOUD_USER -e CCLOUD_PASSWORD=$CCLOUD_PASSWORD dabz/ccloudexporter:latest -cluster $CCLOUD_CLUSTER`? That should fix your issue.

**Comment by Basma1912** [comment]
.
