### ISSUE TITLE
Pod keeps crashing/restarting

### ISSUE THREAD

**Issue by branttaylor** [Dabz/ccloudexporter#36]
We are running this exporter and the Kubernetes pod keeps crashing and restarting. We aren't sure what's happening since no logging is occurring, we just know that the probe on `/metrics` fails and Kubernetes restarts the pod. Is there a way to get additional logging to figure out what's going on?

**Comment by Dabz** [comment]
Hi @branttaylor , 
If there is no log from the exporter, I would assume that there is no issue on the exporter itself. could you share your k8s definition?

My main hypothesis is that `/metrics` timeout and makes Kubernetes think that the POD is unhealthy. When you invoke `/metrics`, queries are synchronously sent to Confluent Cloud Metrics API (to gather the latest metrics), sometime it could require significant time (20, 30 seconds), and it could exceed the configured healthiness/readiness timeout.

Someone opened an issue like this in the past, `/metrics` is probably not a good endpoint to for a liveliness check because:

- It actually sends queries to Confluent Cloud Metrics API (thus, increasing the workload on their side)
- It could take significant time to returns, yet, it does not mean that the exporter is unhealthy

**Comment by branttaylor** [comment]
Okay, thank you for the information! I do agree with the poster on that other issue that a health check endpoint would be nice. Using the `absent` query in Prometheus/AlertManager that you mentioned is a decent second option, but would not cause Kubernetes to automatically restart the pod if it experienced any issues.
