### ISSUE TITLE
Gaps in data due to interval misses

### ISSUE THREAD

**Issue by cotedm** [Dabz/ccloudexporter#4]
I'm seeing pretty regular gaps in the data, probably due to interval misses. I noticed here we're scraping between now and the previous minute:
https://github.com/Dabz/ccloudexporter/blob/master/cmd/internal/scrapper/query.go#L67-L76

If prometheus easily supports updating values, I'd recommend just widening the query window to 5 minutes so you get data points. Updates on the fly would also help with values that are still stabilizing (you'll notice that we expose data right away rather than waiting for late arrivals, then update on the fly).

**Comment by Dabz** [comment]
Instead of scrapping data, the exporter implemented a custom collector in #11 , it is now exposing the metrics with a timestamp (timestamp returned by the API).

It seems that the exposed timestamp will be ignored if it is too old (aka 5 minutes by default),  in order to reduce the problem and to avoid exposing "in-flight" data, only the `current time - 1 minute` is returned for each scrap. This should allow for more predictable and stable results.
