### ISSUE TITLE
Remove superfluous group_by when filtering by single value

### ISSUE THREAD

**Issue by sirianni** [Dabz/ccloudexporter#41]
When the query is filtering to a single `metric.label.cluster_id`:
```json
"filter" : {
  "op": "EQ",
  "field": "metric.label.cluster_id",
  "value": "lkc-12345"
}
```

there is no need to also specify a `group_by`, since we know that all results have the same cluster_id (`lkc-12345` in this example).
```json
"group_by": [
  "metric.label.cluster_id"
]
```

This superfluous group_by causes the query to be more expensive on the backend.  We can explore optimizing this out on the backend, but it is difficult to do since the filter can contain arbitrarily complex boolean expressions.

**Comment by Dabz** [comment]
I started implementing an optimizer to address this point in #44. It was a little bit more challenging than anticipated as, if we are not grouping by a label, we do not get the label value in the backend response. 

e.g., by removing the unnecessary group_by cluster_id, I get:
```
        {
            "metric.label.topic": "damien-topic",
            "timestamp": "2020-09-10T13:37:00Z",
            "value": 0.0
        }
```

instead of 

```
        {
            "metric.label.cluster_id": "lkc-ldrq7",
            "metric.label.partition": "6",
            "metric.label.topic": "damien-topic",
            "timestamp": "2020-09-10T13:37:00Z",
            "value": 0.0
        }
```

I will more thoroughly test this change and merge it later on.

**Comment by Dabz** [comment]
#44 should add this optimization. I am closing this issue for now. Feel free to re-open it if does not behave as expected ;)
