### ISSUE TITLE
Misleading logs for metrics listener

### ISSUE THREAD

**Issue by subkanthi** [Dabz/ccloudexporter#83]
This looks like a substitution error, but its very misleading to think that there is something wrong with the host name

{
  "level": "info",
  "msg": "Listening on http://:2112/metrics\n",
  "time": "2021-07-22T18:34:31Z"
}

**Comment by Dabz** [comment]
Do you mean it's confusing because `Listening` could be understand as network listener? The default Listener is empty, meaning it is listening on all interfaces, I could understand why it could be confusing as I am adding `http://%s/metrics` to it. I will change this log in the next major iteration :+1:

**Comment by Dabz** [comment]
I changed the log message as part of #93 . Somehow, I really struggle to find a good name ^^ Do you have a better idea?
